apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog
spec:
  selector:
    matchLabels:
      app: microblog
  replicas: 2
  template:
    metadata:
      labels:
        app: microblog
    spec:
      containers:
        - image: gufo19/microblog:latest
          imagePullPolicy: Always
          name: microblog
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /
              port: 5000
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: microblog-secrets
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: microblog-secrets
                  key: DB_URL
            - name: container_default_behavior
              value: "compatibility"
            - name: MYSQL_HOST
              value: "mysql"
