version: "3"
services:
    prod:
        image: gufo19/microblog:latest
        container_name: microblog
        restart: always
        environment:
            - SECRET_KEY=c065e2bee1a143a7be1b0321a88bfe0c
            - DATABASE_URL=mysql+pymysql://microblog:password123@dbserver/microblog
        depends_on:
            - "mysql"
        links:
            - mysql:dbserver
        ports:
            - "8000:5000"

    mysql:
        image: mysql/mysql-server:5.7
        container_name: mysql
        restart: always
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=microblog
            - MYSQL_USER=microblog
            - MYSQL_PASSWORD=password123
        volumes:
            - /home/deploy/mysql_data:/var/lib/mysql

    test:
        build:
            context: "./docker/Dockerfile_test"
        image: microblog-test:latest
        volumes:
            - ./:/home/microblog/volume
