version: 2
jobs:
    test:
        machine:
            image: ubuntu-1604:202007-01

        steps:
            - checkout
            - run:
                  name: App test
                  command: docker-compose up test
#     publish:
#         machine:
#             image: ubuntu-1604:202007-01

#         steps:
#             - checkout
#             - run:
#                   name: Publish image
#                   command: |
#                       echo "$DH_PASS" | docker login -u "$DH_USERNAME" --password-stdin
#                       docker build -f docker/Dockerfile_prod -t gufo19/microblog .
#                       docker push gufo19/microblog:latest

workflows:
    version: 2
    build-master:
        jobs:
            - test
            # - publish:
            #       requires:
            #           - test
