version: 2
jobs:
    test:
        machine:
            image: ubuntu-2004:202101-01
        steps:
            - checkout
            - run:
                  name: Run test
                  command: python3 --version
workflows:
    version: 2
    build-master:
        jobs:
            - test
