version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.7

        steps:
            - checkout
            - run:
                  name: Run test
                  command: docker-compose up test
workflows:
    version: 2
    build-master:
        jobs:
            - test
