# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/python:3.7

#     working_directory: ~/repo

#     steps:
#       # Step 1: obtain repo from GitHub
#       - checkout
#       # Step 2: create virtual env and install dependencies
#       - run:
#           name: install dependencies
#           command: |
#             python3 -m venv venv
#             . venv/bin/activate
#             make install-dev
#       # Step 3: run linter and tests
#       - run:
#           name: run tests
#           command: |
#             . venv/bin/activate
#             make test

version: 2
jobs:
    test:
        image: ubuntu-1604:202007-01

        steps:
            - checkout
            - run:
              name: Run test
              command: docker-compose up test

    publish:
        machine:
            image: ubuntu-1604:202007-01

        steps:
            - checkout
            - run:
              name: Publish docker image
              command: |
                  echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                  docker build -f docker/Dockerfile_prod -t gufo19/microblog .
                  docker push gufo19/microblog:latest

workflows:
    version: 2
    build-master:
        jobs:
            - publish:
                  requires:
                      - test
