version: 2.1
# orbs:
#   snyk: snyk/snyk@0.0.8
jobs:
  test:
    machine:
      image: "ubuntu-1604:202007-01"
    steps:
      - checkout
      - run:
          name: Run test
          command: docker-compose up test
  publish:
    machine:
      image: "ubuntu-1604:202007-01"
    steps:
      - checkout
      - run:
          name: Publish docker image
          command: >
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME"
            --password-stdin

            docker build -f docker/Dockerfile_prod -t gufo19/microblog .

            docker push gufo19/microblog:latest
  ansibleAppServer:
    machine:
      image: "ubuntu-1604:202007-01"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            make install-deploy
            pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
      - run:
          name: Run appServer playbook
          command: |
            . venv/bin/activate
            cd ansible
            ansible-playbook -vvv gather_vm_instances.yml appServer.yml
  # snyk:
  #   machine:
  #     image: "ubuntu-1604:202007-01"
  #   steps:
  #     - checkout
  #     - run:
  #         name: install dependencies
  #         command: |
  #           python3 -m venv venv
  #           . venv/bin/activate
  #           make install
  #           make install-deploy
  #     - run: echo "source venv/bin/activate" >> $BASH_ENV # här gör vi så att så att CircleCi automatisk laddar venv och då kollar Snyk vad vi har installerat i den.
  #     - snyk/scan
workflows:
  version: 2
  build-master:
    jobs:
      - test
      # - snyk
      - publish:
          requires:
            - test
            # - snyk
      - ansibleAppServer:
          requires:
            - publish
