FROM python:3.8-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./

RUN python -m venv .venv
ENV FLASK_APP microblog.py
RUN apk add build-base=0.5-r2 --no-cache && \
    .venv/bin/pip3 install -r requirements.txt && \
    chmod +x boot.sh && \
    chown -R microblog:microblog ./

USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]