FROM python:3.8

WORKDIR /home/microblog

# COPY . .
# COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot-test.sh ./

RUN python -m venv .venv
# RUN  apk add sudo && \
#     apk add build-base=0.5-r2 --no-cache && \

RUN /home/microblog/.venv/bin/python -m pip install --upgrade pip && \
    .venv/bin/pip3 install -r requirements/test.txt && \
    chmod +x boot-test.sh

ENV prometheus_multiproc_dir /tmp

ENTRYPOINT ["./boot-test.sh"]