FROM python:3.8

WORKDIR /home/microblog

# COPY . .
# COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot-test.sh ./

RUN python -m venv .venv
RUN apk add build-base=0.5-r2 --no-cache && \
    .venv/bin/pip3 install -r requirements/test.txt && \
    chmod +x boot-test.sh

ENTRYPOINT ["./boot-test.sh"]