---
- name: Copy template
  template:
    src: prometheus.yml.j2
    dest: /tmp/prometheus.yml
    force: yes

- name: docker network
  docker_network:
    name: monitor

- name: prometheus-data volume
  docker_volume:
    name: prometheus-data

- name: get and start node exporter
  docker_container:
    name: prometheus
    image: prom/prometheus:v2.31.1
    restart_policy: unless-stopped
    volumes:
      - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--storage.tsdb.path=/prometheus",
        "--web.console.libraries=/etc/prometheus/console_libraries",
        "--web.console.templates=/etc/prometheus/consoles",
        "--storage.tsdb.retention.time=24h",
        "--web.enable-lifecycle",
      ]
    networks:
      - name: monitor
    ports:
      - "9090:9090"
