---
- hosts: database
  become: true
  become_method: sudo
  remote_user: deploy
  roles:
      - docker

  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
      - name: Create db container
        docker_container:
            name: dbserver
            image: "mysql:5.7"
            restart: true
            ports:
                - "3306:3306"
            env:
                MYSQL_ROOT_PASSWORD: secret
                MYSQL_DATABASE: microblog
                MYSQL_USER: microblog
                MYSQL_PASSWORD: secret
