---
- hosts: loadBalancer
  become: true
  become_method: sudo
  remote_user: deploy
  roles:
    - docker

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install packages
      apt:
        name:
          - nginx
          - python-certbot-nginx
        state: present

    - name: Check if certificate already exists.
      stat:
        path: /etc/letsencrypt/live/gufo.tech/cert.pem
      register: letsencrypt_cert

    - debug: msg="{{ letsencrypt_cert.stat.exists }}"

    - name: Stop services to allow certbot to generate a cert.
      command: service nginx stop
      when: not letsencrypt_cert.stat.exists

    - name: Generate new certificate if one doesn't exist.
      shell: "certbot certonly --standalone --noninteractive --expand --agree-tos --email gufo19@student.bth.se -d gufo.tech -d www.gufo.tech"
      when: not letsencrypt_cert.stat.exists

    - name: Remove default conf
      file:
        state: absent
        path: /etc/nginx/sites-enabled/default

    - name: Copy local nginx.config.j2 to vm
      template:
        src: ./nginx.conf.j2
        dest: /etc/nginx/nginx.conf

    - name: Copy local load-balancer.conf.j2 to vm
      template:
        src: ./load-balancer.conf.j2
        dest: /etc/nginx/sites-available/load-balancer.conf

    - name: Create symbolic link
      file:
        state: link
        src: /etc/nginx/sites-available/load-balancer.conf
        path: /etc/nginx/sites-enabled/load-balancer.conf

    - name: Start nginx
      service:
        name: nginx
        state: started

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes

    - name: get and start nginx exporter
      docker_container:
        name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.4.2
        restart_policy: always
        command:
          [
            "--nginx.scrape-uri=https://gufo.tech/metrics",
            "--nginx.retries=10",
            "--nginx.ssl-verify=false",
            "--web.telemetry-path=/prometheus",
          ]
        ports:
          - "9113:9113"
