---
- hosts: monitoring
  become: true
  become_method: sudo
  remote_user: deploy
  roles:
    - docker
    - node-exporter
    - prometheus
    - grafana

  vars:
    ansible_python_interpreter: /usr/bin/python3
